server:
  port: 9999

briup:
  common:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.101.150.92:3306/ej?characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: system
      




